// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package httpclient

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockExecutor
func (_mock *MockExecutor) Delete(ctx context.Context, path string) (*http.Response, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*http.Response, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *http.Response); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutor_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockExecutor_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockExecutor_Expecter) Delete(ctx interface{}, path interface{}) *MockExecutor_Delete_Call {
	return &MockExecutor_Delete_Call{Call: _e.mock.On("Delete", ctx, path)}
}

func (_c *MockExecutor_Delete_Call) Run(run func(ctx context.Context, path string)) *MockExecutor_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExecutor_Delete_Call) Return(response *http.Response, err error) *MockExecutor_Delete_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockExecutor_Delete_Call) RunAndReturn(run func(ctx context.Context, path string) (*http.Response, error)) *MockExecutor_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJSON provides a mock function for the type MockExecutor
func (_mock *MockExecutor) DeleteJSON(ctx context.Context, path string, result any) error {
	ret := _mock.Called(ctx, path, result)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, path, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutor_DeleteJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJSON'
type MockExecutor_DeleteJSON_Call struct {
	*mock.Call
}

// DeleteJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - result any
func (_e *MockExecutor_Expecter) DeleteJSON(ctx interface{}, path interface{}, result interface{}) *MockExecutor_DeleteJSON_Call {
	return &MockExecutor_DeleteJSON_Call{Call: _e.mock.On("DeleteJSON", ctx, path, result)}
}

func (_c *MockExecutor_DeleteJSON_Call) Run(run func(ctx context.Context, path string, result any)) *MockExecutor_DeleteJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExecutor_DeleteJSON_Call) Return(err error) *MockExecutor_DeleteJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutor_DeleteJSON_Call) RunAndReturn(run func(ctx context.Context, path string, result any) error) *MockExecutor_DeleteJSON_Call {
	_c.Call.Return(run)
	return _c
}

// Do provides a mock function for the type MockExecutor
func (_mock *MockExecutor) Do(ctx context.Context, method string, path string, body any) (*http.Response, error) {
	ret := _mock.Called(ctx, method, path, body)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any) (*http.Response, error)); ok {
		return returnFunc(ctx, method, path, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any) *http.Response); ok {
		r0 = returnFunc(ctx, method, path, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, any) error); ok {
		r1 = returnFunc(ctx, method, path, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutor_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockExecutor_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
//   - body any
func (_e *MockExecutor_Expecter) Do(ctx interface{}, method interface{}, path interface{}, body interface{}) *MockExecutor_Do_Call {
	return &MockExecutor_Do_Call{Call: _e.mock.On("Do", ctx, method, path, body)}
}

func (_c *MockExecutor_Do_Call) Run(run func(ctx context.Context, method string, path string, body any)) *MockExecutor_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockExecutor_Do_Call) Return(response *http.Response, err error) *MockExecutor_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockExecutor_Do_Call) RunAndReturn(run func(ctx context.Context, method string, path string, body any) (*http.Response, error)) *MockExecutor_Do_Call {
	_c.Call.Return(run)
	return _c
}

// DoWithResponse provides a mock function for the type MockExecutor
func (_mock *MockExecutor) DoWithResponse(ctx context.Context, method string, path string, body any, result any) error {
	ret := _mock.Called(ctx, method, path, body, result)

	if len(ret) == 0 {
		panic("no return value specified for DoWithResponse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any, any) error); ok {
		r0 = returnFunc(ctx, method, path, body, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutor_DoWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWithResponse'
type MockExecutor_DoWithResponse_Call struct {
	*mock.Call
}

// DoWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
//   - body any
//   - result any
func (_e *MockExecutor_Expecter) DoWithResponse(ctx interface{}, method interface{}, path interface{}, body interface{}, result interface{}) *MockExecutor_DoWithResponse_Call {
	return &MockExecutor_DoWithResponse_Call{Call: _e.mock.On("DoWithResponse", ctx, method, path, body, result)}
}

func (_c *MockExecutor_DoWithResponse_Call) Run(run func(ctx context.Context, method string, path string, body any, result any)) *MockExecutor_DoWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockExecutor_DoWithResponse_Call) Return(err error) *MockExecutor_DoWithResponse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutor_DoWithResponse_Call) RunAndReturn(run func(ctx context.Context, method string, path string, body any, result any) error) *MockExecutor_DoWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockExecutor
func (_mock *MockExecutor) Get(ctx context.Context, path string) (*http.Response, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*http.Response, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *http.Response); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutor_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockExecutor_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockExecutor_Expecter) Get(ctx interface{}, path interface{}) *MockExecutor_Get_Call {
	return &MockExecutor_Get_Call{Call: _e.mock.On("Get", ctx, path)}
}

func (_c *MockExecutor_Get_Call) Run(run func(ctx context.Context, path string)) *MockExecutor_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExecutor_Get_Call) Return(response *http.Response, err error) *MockExecutor_Get_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockExecutor_Get_Call) RunAndReturn(run func(ctx context.Context, path string) (*http.Response, error)) *MockExecutor_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetErrorParser provides a mock function for the type MockExecutor
func (_mock *MockExecutor) GetErrorParser() *ErrorParserChain {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetErrorParser")
	}

	var r0 *ErrorParserChain
	if returnFunc, ok := ret.Get(0).(func() *ErrorParserChain); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ErrorParserChain)
		}
	}
	return r0
}

// MockExecutor_GetErrorParser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetErrorParser'
type MockExecutor_GetErrorParser_Call struct {
	*mock.Call
}

// GetErrorParser is a helper method to define mock.On call
func (_e *MockExecutor_Expecter) GetErrorParser() *MockExecutor_GetErrorParser_Call {
	return &MockExecutor_GetErrorParser_Call{Call: _e.mock.On("GetErrorParser")}
}

func (_c *MockExecutor_GetErrorParser_Call) Run(run func()) *MockExecutor_GetErrorParser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExecutor_GetErrorParser_Call) Return(errorParserChain *ErrorParserChain) *MockExecutor_GetErrorParser_Call {
	_c.Call.Return(errorParserChain)
	return _c
}

func (_c *MockExecutor_GetErrorParser_Call) RunAndReturn(run func() *ErrorParserChain) *MockExecutor_GetErrorParser_Call {
	_c.Call.Return(run)
	return _c
}

// GetHTTPClient provides a mock function for the type MockExecutor
func (_mock *MockExecutor) GetHTTPClient() *http.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHTTPClient")
	}

	var r0 *http.Client
	if returnFunc, ok := ret.Get(0).(func() *http.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}
	return r0
}

// MockExecutor_GetHTTPClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHTTPClient'
type MockExecutor_GetHTTPClient_Call struct {
	*mock.Call
}

// GetHTTPClient is a helper method to define mock.On call
func (_e *MockExecutor_Expecter) GetHTTPClient() *MockExecutor_GetHTTPClient_Call {
	return &MockExecutor_GetHTTPClient_Call{Call: _e.mock.On("GetHTTPClient")}
}

func (_c *MockExecutor_GetHTTPClient_Call) Run(run func()) *MockExecutor_GetHTTPClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExecutor_GetHTTPClient_Call) Return(client *http.Client) *MockExecutor_GetHTTPClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockExecutor_GetHTTPClient_Call) RunAndReturn(run func() *http.Client) *MockExecutor_GetHTTPClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetJSON provides a mock function for the type MockExecutor
func (_mock *MockExecutor) GetJSON(ctx context.Context, path string, result any) error {
	ret := _mock.Called(ctx, path, result)

	if len(ret) == 0 {
		panic("no return value specified for GetJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, path, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutor_GetJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJSON'
type MockExecutor_GetJSON_Call struct {
	*mock.Call
}

// GetJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - result any
func (_e *MockExecutor_Expecter) GetJSON(ctx interface{}, path interface{}, result interface{}) *MockExecutor_GetJSON_Call {
	return &MockExecutor_GetJSON_Call{Call: _e.mock.On("GetJSON", ctx, path, result)}
}

func (_c *MockExecutor_GetJSON_Call) Run(run func(ctx context.Context, path string, result any)) *MockExecutor_GetJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExecutor_GetJSON_Call) Return(err error) *MockExecutor_GetJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutor_GetJSON_Call) RunAndReturn(run func(ctx context.Context, path string, result any) error) *MockExecutor_GetJSON_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockExecutor
func (_mock *MockExecutor) Patch(ctx context.Context, path string, body any) (*http.Response, error) {
	ret := _mock.Called(ctx, path, body)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) (*http.Response, error)); ok {
		return returnFunc(ctx, path, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) *http.Response); ok {
		r0 = returnFunc(ctx, path, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = returnFunc(ctx, path, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutor_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockExecutor_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - body any
func (_e *MockExecutor_Expecter) Patch(ctx interface{}, path interface{}, body interface{}) *MockExecutor_Patch_Call {
	return &MockExecutor_Patch_Call{Call: _e.mock.On("Patch", ctx, path, body)}
}

func (_c *MockExecutor_Patch_Call) Run(run func(ctx context.Context, path string, body any)) *MockExecutor_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExecutor_Patch_Call) Return(response *http.Response, err error) *MockExecutor_Patch_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockExecutor_Patch_Call) RunAndReturn(run func(ctx context.Context, path string, body any) (*http.Response, error)) *MockExecutor_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// PatchJSON provides a mock function for the type MockExecutor
func (_mock *MockExecutor) PatchJSON(ctx context.Context, path string, body any, result any) error {
	ret := _mock.Called(ctx, path, body, result)

	if len(ret) == 0 {
		panic("no return value specified for PatchJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any) error); ok {
		r0 = returnFunc(ctx, path, body, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutor_PatchJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchJSON'
type MockExecutor_PatchJSON_Call struct {
	*mock.Call
}

// PatchJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - body any
//   - result any
func (_e *MockExecutor_Expecter) PatchJSON(ctx interface{}, path interface{}, body interface{}, result interface{}) *MockExecutor_PatchJSON_Call {
	return &MockExecutor_PatchJSON_Call{Call: _e.mock.On("PatchJSON", ctx, path, body, result)}
}

func (_c *MockExecutor_PatchJSON_Call) Run(run func(ctx context.Context, path string, body any, result any)) *MockExecutor_PatchJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockExecutor_PatchJSON_Call) Return(err error) *MockExecutor_PatchJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutor_PatchJSON_Call) RunAndReturn(run func(ctx context.Context, path string, body any, result any) error) *MockExecutor_PatchJSON_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function for the type MockExecutor
func (_mock *MockExecutor) Post(ctx context.Context, path string, body any) (*http.Response, error) {
	ret := _mock.Called(ctx, path, body)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) (*http.Response, error)); ok {
		return returnFunc(ctx, path, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) *http.Response); ok {
		r0 = returnFunc(ctx, path, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = returnFunc(ctx, path, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutor_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockExecutor_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - body any
func (_e *MockExecutor_Expecter) Post(ctx interface{}, path interface{}, body interface{}) *MockExecutor_Post_Call {
	return &MockExecutor_Post_Call{Call: _e.mock.On("Post", ctx, path, body)}
}

func (_c *MockExecutor_Post_Call) Run(run func(ctx context.Context, path string, body any)) *MockExecutor_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExecutor_Post_Call) Return(response *http.Response, err error) *MockExecutor_Post_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockExecutor_Post_Call) RunAndReturn(run func(ctx context.Context, path string, body any) (*http.Response, error)) *MockExecutor_Post_Call {
	_c.Call.Return(run)
	return _c
}

// PostJSON provides a mock function for the type MockExecutor
func (_mock *MockExecutor) PostJSON(ctx context.Context, path string, body any, result any) error {
	ret := _mock.Called(ctx, path, body, result)

	if len(ret) == 0 {
		panic("no return value specified for PostJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any) error); ok {
		r0 = returnFunc(ctx, path, body, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutor_PostJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostJSON'
type MockExecutor_PostJSON_Call struct {
	*mock.Call
}

// PostJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - body any
//   - result any
func (_e *MockExecutor_Expecter) PostJSON(ctx interface{}, path interface{}, body interface{}, result interface{}) *MockExecutor_PostJSON_Call {
	return &MockExecutor_PostJSON_Call{Call: _e.mock.On("PostJSON", ctx, path, body, result)}
}

func (_c *MockExecutor_PostJSON_Call) Run(run func(ctx context.Context, path string, body any, result any)) *MockExecutor_PostJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockExecutor_PostJSON_Call) Return(err error) *MockExecutor_PostJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutor_PostJSON_Call) RunAndReturn(run func(ctx context.Context, path string, body any, result any) error) *MockExecutor_PostJSON_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockExecutor
func (_mock *MockExecutor) Put(ctx context.Context, path string, body any) (*http.Response, error) {
	ret := _mock.Called(ctx, path, body)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) (*http.Response, error)); ok {
		return returnFunc(ctx, path, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) *http.Response); ok {
		r0 = returnFunc(ctx, path, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = returnFunc(ctx, path, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutor_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockExecutor_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - body any
func (_e *MockExecutor_Expecter) Put(ctx interface{}, path interface{}, body interface{}) *MockExecutor_Put_Call {
	return &MockExecutor_Put_Call{Call: _e.mock.On("Put", ctx, path, body)}
}

func (_c *MockExecutor_Put_Call) Run(run func(ctx context.Context, path string, body any)) *MockExecutor_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExecutor_Put_Call) Return(response *http.Response, err error) *MockExecutor_Put_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockExecutor_Put_Call) RunAndReturn(run func(ctx context.Context, path string, body any) (*http.Response, error)) *MockExecutor_Put_Call {
	_c.Call.Return(run)
	return _c
}

// PutJSON provides a mock function for the type MockExecutor
func (_mock *MockExecutor) PutJSON(ctx context.Context, path string, body any, result any) error {
	ret := _mock.Called(ctx, path, body, result)

	if len(ret) == 0 {
		panic("no return value specified for PutJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any) error); ok {
		r0 = returnFunc(ctx, path, body, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutor_PutJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutJSON'
type MockExecutor_PutJSON_Call struct {
	*mock.Call
}

// PutJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - body any
//   - result any
func (_e *MockExecutor_Expecter) PutJSON(ctx interface{}, path interface{}, body interface{}, result interface{}) *MockExecutor_PutJSON_Call {
	return &MockExecutor_PutJSON_Call{Call: _e.mock.On("PutJSON", ctx, path, body, result)}
}

func (_c *MockExecutor_PutJSON_Call) Run(run func(ctx context.Context, path string, body any, result any)) *MockExecutor_PutJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockExecutor_PutJSON_Call) Return(err error) *MockExecutor_PutJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutor_PutJSON_Call) RunAndReturn(run func(ctx context.Context, path string, body any, result any) error) *MockExecutor_PutJSON_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveHeader provides a mock function for the type MockExecutor
func (_mock *MockExecutor) RemoveHeader(key string) {
	_mock.Called(key)
	return
}

// MockExecutor_RemoveHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveHeader'
type MockExecutor_RemoveHeader_Call struct {
	*mock.Call
}

// RemoveHeader is a helper method to define mock.On call
//   - key string
func (_e *MockExecutor_Expecter) RemoveHeader(key interface{}) *MockExecutor_RemoveHeader_Call {
	return &MockExecutor_RemoveHeader_Call{Call: _e.mock.On("RemoveHeader", key)}
}

func (_c *MockExecutor_RemoveHeader_Call) Run(run func(key string)) *MockExecutor_RemoveHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExecutor_RemoveHeader_Call) Return() *MockExecutor_RemoveHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutor_RemoveHeader_Call) RunAndReturn(run func(key string)) *MockExecutor_RemoveHeader_Call {
	_c.Run(run)
	return _c
}

// SetBaseURL provides a mock function for the type MockExecutor
func (_mock *MockExecutor) SetBaseURL(baseURL string) {
	_mock.Called(baseURL)
	return
}

// MockExecutor_SetBaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBaseURL'
type MockExecutor_SetBaseURL_Call struct {
	*mock.Call
}

// SetBaseURL is a helper method to define mock.On call
//   - baseURL string
func (_e *MockExecutor_Expecter) SetBaseURL(baseURL interface{}) *MockExecutor_SetBaseURL_Call {
	return &MockExecutor_SetBaseURL_Call{Call: _e.mock.On("SetBaseURL", baseURL)}
}

func (_c *MockExecutor_SetBaseURL_Call) Run(run func(baseURL string)) *MockExecutor_SetBaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExecutor_SetBaseURL_Call) Return() *MockExecutor_SetBaseURL_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutor_SetBaseURL_Call) RunAndReturn(run func(baseURL string)) *MockExecutor_SetBaseURL_Call {
	_c.Run(run)
	return _c
}

// SetErrorParser provides a mock function for the type MockExecutor
func (_mock *MockExecutor) SetErrorParser(parser *ErrorParserChain) {
	_mock.Called(parser)
	return
}

// MockExecutor_SetErrorParser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetErrorParser'
type MockExecutor_SetErrorParser_Call struct {
	*mock.Call
}

// SetErrorParser is a helper method to define mock.On call
//   - parser *ErrorParserChain
func (_e *MockExecutor_Expecter) SetErrorParser(parser interface{}) *MockExecutor_SetErrorParser_Call {
	return &MockExecutor_SetErrorParser_Call{Call: _e.mock.On("SetErrorParser", parser)}
}

func (_c *MockExecutor_SetErrorParser_Call) Run(run func(parser *ErrorParserChain)) *MockExecutor_SetErrorParser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ErrorParserChain
		if args[0] != nil {
			arg0 = args[0].(*ErrorParserChain)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExecutor_SetErrorParser_Call) Return() *MockExecutor_SetErrorParser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutor_SetErrorParser_Call) RunAndReturn(run func(parser *ErrorParserChain)) *MockExecutor_SetErrorParser_Call {
	_c.Run(run)
	return _c
}

// SetHTTPClient provides a mock function for the type MockExecutor
func (_mock *MockExecutor) SetHTTPClient(httpClient *http.Client) {
	_mock.Called(httpClient)
	return
}

// MockExecutor_SetHTTPClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHTTPClient'
type MockExecutor_SetHTTPClient_Call struct {
	*mock.Call
}

// SetHTTPClient is a helper method to define mock.On call
//   - httpClient *http.Client
func (_e *MockExecutor_Expecter) SetHTTPClient(httpClient interface{}) *MockExecutor_SetHTTPClient_Call {
	return &MockExecutor_SetHTTPClient_Call{Call: _e.mock.On("SetHTTPClient", httpClient)}
}

func (_c *MockExecutor_SetHTTPClient_Call) Run(run func(httpClient *http.Client)) *MockExecutor_SetHTTPClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Client
		if args[0] != nil {
			arg0 = args[0].(*http.Client)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExecutor_SetHTTPClient_Call) Return() *MockExecutor_SetHTTPClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutor_SetHTTPClient_Call) RunAndReturn(run func(httpClient *http.Client)) *MockExecutor_SetHTTPClient_Call {
	_c.Run(run)
	return _c
}

// SetHeader provides a mock function for the type MockExecutor
func (_mock *MockExecutor) SetHeader(key string, value string) {
	_mock.Called(key, value)
	return
}

// MockExecutor_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockExecutor_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockExecutor_Expecter) SetHeader(key interface{}, value interface{}) *MockExecutor_SetHeader_Call {
	return &MockExecutor_SetHeader_Call{Call: _e.mock.On("SetHeader", key, value)}
}

func (_c *MockExecutor_SetHeader_Call) Run(run func(key string, value string)) *MockExecutor_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExecutor_SetHeader_Call) Return() *MockExecutor_SetHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutor_SetHeader_Call) RunAndReturn(run func(key string, value string)) *MockExecutor_SetHeader_Call {
	_c.Run(run)
	return _c
}

// SetHeaders provides a mock function for the type MockExecutor
func (_mock *MockExecutor) SetHeaders(headers map[string]string) {
	_mock.Called(headers)
	return
}

// MockExecutor_SetHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeaders'
type MockExecutor_SetHeaders_Call struct {
	*mock.Call
}

// SetHeaders is a helper method to define mock.On call
//   - headers map[string]string
func (_e *MockExecutor_Expecter) SetHeaders(headers interface{}) *MockExecutor_SetHeaders_Call {
	return &MockExecutor_SetHeaders_Call{Call: _e.mock.On("SetHeaders", headers)}
}

func (_c *MockExecutor_SetHeaders_Call) Run(run func(headers map[string]string)) *MockExecutor_SetHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]string
		if args[0] != nil {
			arg0 = args[0].(map[string]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExecutor_SetHeaders_Call) Return() *MockExecutor_SetHeaders_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutor_SetHeaders_Call) RunAndReturn(run func(headers map[string]string)) *MockExecutor_SetHeaders_Call {
	_c.Run(run)
	return _c
}

// NewMockErrorResponseParser creates a new instance of MockErrorResponseParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorResponseParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorResponseParser {
	mock := &MockErrorResponseParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockErrorResponseParser is an autogenerated mock type for the ErrorResponseParser type
type MockErrorResponseParser struct {
	mock.Mock
}

type MockErrorResponseParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorResponseParser) EXPECT() *MockErrorResponseParser_Expecter {
	return &MockErrorResponseParser_Expecter{mock: &_m.Mock}
}

// CanParse provides a mock function for the type MockErrorResponseParser
func (_mock *MockErrorResponseParser) CanParse(body []byte) bool {
	ret := _mock.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for CanParse")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func([]byte) bool); ok {
		r0 = returnFunc(body)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockErrorResponseParser_CanParse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanParse'
type MockErrorResponseParser_CanParse_Call struct {
	*mock.Call
}

// CanParse is a helper method to define mock.On call
//   - body []byte
func (_e *MockErrorResponseParser_Expecter) CanParse(body interface{}) *MockErrorResponseParser_CanParse_Call {
	return &MockErrorResponseParser_CanParse_Call{Call: _e.mock.On("CanParse", body)}
}

func (_c *MockErrorResponseParser_CanParse_Call) Run(run func(body []byte)) *MockErrorResponseParser_CanParse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockErrorResponseParser_CanParse_Call) Return(b bool) *MockErrorResponseParser_CanParse_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockErrorResponseParser_CanParse_Call) RunAndReturn(run func(body []byte) bool) *MockErrorResponseParser_CanParse_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function for the type MockErrorResponseParser
func (_mock *MockErrorResponseParser) Parse(body []byte) (*ParsedErrorResponse, error) {
	ret := _mock.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *ParsedErrorResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*ParsedErrorResponse, error)); ok {
		return returnFunc(body)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *ParsedErrorResponse); ok {
		r0 = returnFunc(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ParsedErrorResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockErrorResponseParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockErrorResponseParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - body []byte
func (_e *MockErrorResponseParser_Expecter) Parse(body interface{}) *MockErrorResponseParser_Parse_Call {
	return &MockErrorResponseParser_Parse_Call{Call: _e.mock.On("Parse", body)}
}

func (_c *MockErrorResponseParser_Parse_Call) Run(run func(body []byte)) *MockErrorResponseParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockErrorResponseParser_Parse_Call) Return(parsedErrorResponse *ParsedErrorResponse, err error) *MockErrorResponseParser_Parse_Call {
	_c.Call.Return(parsedErrorResponse, err)
	return _c
}

func (_c *MockErrorResponseParser_Parse_Call) RunAndReturn(run func(body []byte) (*ParsedErrorResponse, error)) *MockErrorResponseParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
